apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: toocooluser
  MONGO_INITDB_ROOT_PASSWORD: toocool123
  MONGO_USERNAME: cooluser
  MONGO_PASSWORD: verycool123
